# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FInalProjectApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'BulletinBoard'

  target 'FInalProjectAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FInalProjectAppUITests' do
    # Pods for testing
  end

end
